agent_proposals:
  enabled: true
  complexity_thresholds:
    simple: 0.3
    complex: 0.7
    enterprise: 0.9
  
  # Chutes-specific configuration
  chutes_config:
    model: "deepseek-ai/DeepSeek-V3-0324"  # or your preferred model
    temperature: 0.7
    max_tokens: 2048
    json_mode: true  # If Chutes supports JSON mode
    
  templates:
    - name: "banking_specialist"
      path: "agent_proposals/templates/banking_agent_template.py"
    - name: "compliance_officer"
      path: "agent_proposals/templates/compliance_agent_template.py"
      
  a2a_config:
    enabled: false
    protocol_version: "1.0"